#ifndef STATISTICAL_ANALYSIS_OF_DIGITAL_IMAGES_CORRELATION_H
#define STATISTICAL_ANALYSIS_OF_DIGITAL_IMAGES_CORRELATION_H

#include "stdexcept"
#include "numeric"
#include "../bmp/bmp.h"


#endif //STATISTICAL_ANALYSIS_OF_DIGITAL_IMAGES_CORRELATION_H
